import { createExecutionPlan } from "../connect/executionPlanner.js";
import { canExecute } from "./capabilityRegistry.js";
import { selectTool as selectToolContract } from "./modelToolContracts.js";

const EXTERNAL_ACTIONS = new Set([
  "publish",
  "publishing",
  "external_publish",
  "publish_to_youtube",
  "publish_to_social",
  "paid_action",
  "delete_project",
  "destructive_action"
]);

const ACTION_CAPABILITIES = {
  create_chapter_structure: {
    capabilityId: "production_chapter_outline",
    capability: "text_generation",
    category: "ai_model",
    permissionLevel: "GENERATE_INTERNAL",
    toolAction: "create_chapter_outline"
  },
  create_chapter_draft: {
    capabilityId: "production_chapter_draft",
    capability: "document_generation",
    category: "documents",
    permissionLevel: "GENERATE_INTERNAL",
    toolAction: "create_chapter_draft"
  },
  save_chapter_artifact: {
    capabilityId: "internal_project_save",
    capability: "project_storage",
    category: "storage",
    permissionLevel: "SAVE_INTERNAL",
    toolAction: "save_artifact"
  },
  verify_chapter_result: {
    capabilityId: "internal_artifact_update",
    capability: "brief_generation",
    category: "documents",
    permissionLevel: "READ",
    toolAction: "update_project_state"
  }
};

function createId(prefix = "tool") {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function nowIso() {
  return new Date().toISOString();
}

function getAnswer(answers = {}, key, fallback = "Not specified") {
  const value = String(answers[key] || answers[String(key)] || "").trim();
  return value || fallback;
}

function isExternalAction(action = "") {
  const text = String(action || "").toLowerCase();

  return EXTERNAL_ACTIONS.has(text) ||
    text.includes("publish") ||
    text.includes("external") ||
    text.includes("paid") ||
    text.includes("delete") ||
    text.includes("destructive");
}

function cloneProject(project = null) {
  return project ? {
    ...project,
    artifacts: Array.isArray(project.artifacts) ? [...project.artifacts] : [],
    assets: {
      ...(project.assets || {}),
      documents: Array.isArray(project.assets?.documents) ? [...project.assets.documents] : []
    },
    history: Array.isArray(project.history) ? [...project.history] : []
  } : null;
}

function buildToolRequest({
  task = null,
  capability = null,
  input = {},
  project = null,
  workflowState = {},
  goalState = {},
  permissions = {},
  contextPack = null
} = {}) {
  const action = task?.action || input.nextAction || workflowState.goalProgress?.nextBestStep || "respond";
  const mapped = ACTION_CAPABILITIES[action] || {
    capabilityId: capability || null,
    capability: capability || "brief_generation",
    category: "documents",
    permissionLevel: "READ",
    toolAction: action
  };
  const traceId = input.traceId || contextPack?.traceId || createId("trace");

  return {
    taskId: task?.taskId || createId("task"),
    goalId: goalState?.goalId || workflowState?.goalId || project?.goalId || null,
    projectId: project?.id || workflowState?.linkedProjectId || null,
    workflowId: workflowState?.workflow || project?.workflowId || null,
    action,
    capabilityId: mapped.capabilityId,
    capability: capability || mapped.capability,
    category: mapped.category,
    input,
    artifactTarget: input.artifactTarget || (action === "create_chapter_draft" ? "chapter_draft" : null),
    permissionLevel: mapped.permissionLevel,
    toolAction: mapped.toolAction,
    traceId
  };
}

function buildChapterDraftContent({ workflowState = {}, project = null } = {}) {
  const answers = workflowState.answers || {};
  const topic = getAnswer(answers, 0, project?.title || "Chapter");
  const bookContext = getAnswer(answers, 1);
  const style = getAnswer(answers, 2);
  const effect = getAnswer(answers, 3);
  const existingMaterial = getAnswer(answers, 4, "No existing material");
  const outline = (project?.artifacts || []).find((artifact) => artifact.type === "chapter_outline");

  return [
    "# Chapter Draft",
    "",
    `Topic: ${topic}`,
    `Book / context: ${bookContext}`,
    `Style: ${style}`,
    `Desired reader effect: ${effect}`,
    `Existing material: ${existingMaterial}`,
    "",
    "## Draft",
    "",
    `This is an internal local draft for the chapter about ${topic}.`,
    "",
    "The chapter opens with the central question and turns it into a clear movement for the reader. It connects the theme to the wider book context, keeps the promised style, and preserves the intended emotional result.",
    "",
    "### Working Structure",
    outline?.content
      ? outline.content
      : "1. Opening question.\n2. Core idea.\n3. Development.\n4. Reader turn.\n5. Closing bridge.",
    "",
    "### Notes",
    "Generated by ESSA local internal execution for pipeline validation. No external model or publishing provider was called."
  ].join("\n");
}

function upsertArtifact(project, artifact) {
  const artifacts = Array.isArray(project.artifacts) ? [...project.artifacts] : [];
  const existingIndex = artifacts.findIndex((item) =>
    item.type === artifact.type && item.sourceStepId === artifact.sourceStepId
  );
  const operation = existingIndex >= 0 ? "updated" : "created";
  const nextArtifact = existingIndex >= 0
    ? {
      ...artifacts[existingIndex],
      ...artifact,
      id: artifacts[existingIndex].id,
      createdAt: artifacts[existingIndex].createdAt || artifact.createdAt,
      updatedAt: artifact.updatedAt
    }
    : artifact;

  if (existingIndex >= 0) {
    artifacts[existingIndex] = nextArtifact;
  } else {
    artifacts.push(nextArtifact);
  }

  const documents = Array.isArray(project.assets?.documents) ? [...project.assets.documents] : [];
  const documentIndex = documents.findIndex((item) => item.id === nextArtifact.id);

  if (documentIndex >= 0) {
    documents[documentIndex] = nextArtifact;
  } else {
    documents.push(nextArtifact);
  }

  return {
    operation,
    artifact: nextArtifact,
    project: {
      ...project,
      artifacts,
      assets: {
        ...(project.assets || {}),
        documents
      }
    }
  };
}

function createFailedResult(toolRequest, selectedTool, error, executionTrace = []) {
  return {
    ok: false,
    toolId: selectedTool?.id || null,
    action: toolRequest.action,
    output: null,
    artifacts: [],
    projectUpdates: null,
    workflowUpdates: null,
    error: error.message || String(error),
    requiresConfirmation: false,
    executionTrace: [
      ...executionTrace,
      {
        event: "tool_failed",
        traceId: toolRequest.traceId,
        error: error.message || String(error),
        createdAt: nowIso()
      }
    ],
    toolRequest,
    selectedTool
  };
}

function executeCreateChapterDraft({ toolRequest, selectedTool, project, workflowState, goalState }) {
  if (!project?.id) {
    throw new Error("Project is required for create_chapter_draft");
  }

  const createdAt = nowIso();
  const content = buildChapterDraftContent({ workflowState, project });
  const artifact = {
    id: createId("artifact"),
    projectId: project.id,
    type: "chapter_draft",
    title: `${project.title || "Chapter"} Draft`,
    content,
    status: "saved",
    sourceStepId: "create_chapter_draft",
    createdAt,
    updatedAt: createdAt
  };
  const upsert = upsertArtifact(project, artifact);
  const history = [
    ...(Array.isArray(upsert.project.history) ? upsert.project.history : []),
    {
      id: createId("history"),
      event: upsert.operation === "created" ? "artifact_created" : "artifact_updated",
      artifactId: upsert.artifact.id,
      artifactType: upsert.artifact.type,
      goalId: goalState?.goalId || workflowState.goalId || null,
      workflowId: workflowState.workflow || "production_book",
      traceId: toolRequest.traceId,
      createdAt
    }
  ];
  const nextGoalState = {
    ...(goalState || workflowState.goalState || {}),
    linkedProjectId: project.id,
    progress: {
      ...(goalState?.progress || workflowState.goalState?.progress || {}),
      draft_created: true,
      artifact_saved: true
    },
    updatedAt: createdAt
  };
  const workflowUpdates = {
    ...workflowState,
    linkedProjectId: project.id,
    draftCreated: true,
    artifactSaved: true,
    goalState: nextGoalState
  };
  const projectUpdates = {
    ...upsert.project,
    status: "in_progress",
    workflowState: workflowUpdates,
    goalState: nextGoalState,
    history,
    updatedAt: createdAt
  };

  return {
    ok: true,
    toolId: selectedTool?.id || "essa_documents",
    action: toolRequest.action,
    output: {
      message: "chapter_draft artifact created by internal local execution",
      operation: upsert.operation
    },
    artifacts: [upsert.artifact],
    projectUpdates,
    workflowUpdates,
    error: null,
    requiresConfirmation: false,
    executionTrace: [
      { event: "tool_started", traceId: toolRequest.traceId, toolId: selectedTool?.id || null, createdAt },
      { event: "artifact_created", traceId: toolRequest.traceId, artifactId: upsert.artifact.id, operation: upsert.operation, createdAt },
      { event: "tool_completed", traceId: toolRequest.traceId, toolId: selectedTool?.id || null, createdAt }
    ],
    toolRequest,
    selectedTool
  };
}

export function executeToolRequest({
  task = null,
  capability = null,
  input = {},
  project = null,
  workflowState = {},
  goalState = {},
  permissions = {},
  contextPack = null
} = {}) {
  const toolRequest = buildToolRequest({
    task,
    capability,
    input,
    project,
    workflowState,
    goalState,
    permissions,
    contextPack
  });
  const executionTrace = [
    { event: "tool_requested", traceId: toolRequest.traceId, action: toolRequest.action, createdAt: nowIso() }
  ];

  if (input.simulateToolFailure || permissions.simulateToolFailure) {
    return createFailedResult(toolRequest, null, new Error("simulated tool failure"), executionTrace);
  }

  const capabilityCheck = canExecute(toolRequest.capabilityId, toolRequest.action, { permissions });

  if (!capabilityCheck.executable) {
    return {
      ok: false,
      toolId: null,
      action: toolRequest.action,
      output: null,
      artifacts: [],
      projectUpdates: null,
      workflowUpdates: null,
      error: capabilityCheck.blockingReason,
      requiresConfirmation: capabilityCheck.requiresConfirmation,
      executionTrace: [
        ...executionTrace,
        {
          event: "capability_blocked",
          traceId: toolRequest.traceId,
          capabilityId: toolRequest.capabilityId,
          status: capabilityCheck.status,
          blockingReason: capabilityCheck.blockingReason,
          createdAt: nowIso()
        }
      ],
      toolRequest,
      selectedTool: null,
      capabilityCheck
    };
  }

  if (
    isExternalAction(toolRequest.action) ||
    ["PUBLISH", "EXTERNAL_ACTION", "PAID_ACTION", "DESTRUCTIVE_ACTION"].includes(toolRequest.permissionLevel) ||
    permissions.allowExternalActions === false
  ) {
    return {
      ok: false,
      toolId: null,
      action: toolRequest.action,
      output: null,
      artifacts: [],
      projectUpdates: null,
      workflowUpdates: null,
      error: null,
      requiresConfirmation: true,
      executionTrace: [
        ...executionTrace,
        { event: "confirmation_required", traceId: toolRequest.traceId, action: toolRequest.action, createdAt: nowIso() }
      ],
      toolRequest,
      selectedTool: null
    };
  }

  if (!["READ", "GENERATE_INTERNAL", "SAVE_INTERNAL", "MODIFY_DRAFT"].includes(toolRequest.permissionLevel)) {
    return {
      ok: false,
      toolId: null,
      action: toolRequest.action,
      output: null,
      artifacts: [],
      projectUpdates: null,
      workflowUpdates: null,
      error: `permission denied for ${toolRequest.permissionLevel}`,
      requiresConfirmation: true,
      executionTrace,
      toolRequest,
      selectedTool: null
    };
  }

  const executionPlan = project ? createExecutionPlan(project) : null;
  const selection = selectToolContract({
    action: toolRequest.action,
    capability: toolRequest.capabilityId,
    permissions,
    health: capabilityCheck.health,
    costPolicy: "included"
  });
  const selectedTool = selection.selected;

  try {
    if (toolRequest.action === "create_chapter_draft") {
      const result = executeCreateChapterDraft({
        toolRequest,
        selectedTool,
        project: cloneProject(project),
        workflowState,
        goalState
      });

      return {
        ...result,
        executionTrace: [
          ...executionTrace,
          { event: "selected_tool", traceId: toolRequest.traceId, capabilityId: toolRequest.capabilityId, toolId: selectedTool?.id || null, createdAt: nowIso() },
          ...result.executionTrace
        ],
        executionPlan,
        capabilityCheck
      };
    }

    return {
      ok: false,
      toolId: selectedTool?.id || null,
      action: toolRequest.action,
      output: {
        message: "no internal executor for action in Phase 8"
      },
      artifacts: [],
      projectUpdates: project || null,
      workflowUpdates: workflowState || null,
      error: null,
      requiresConfirmation: false,
      executionTrace: [
        ...executionTrace,
        { event: "tool_completed", traceId: toolRequest.traceId, toolId: selectedTool?.id || null, note: "no_op", createdAt: nowIso() }
      ],
      toolRequest,
      selectedTool,
      executionPlan,
      capabilityCheck
    };
  } catch (error) {
    return {
      ...createFailedResult(toolRequest, selectedTool, error, executionTrace),
      executionPlan,
      capabilityCheck
    };
  }
}
