export const productIds = {
  navigator: "ESSA_NAVIGATOR",
  production: "ESSA_PRODUCTION",
  musicFactory: "ESSA_MUSIC_FACTORY",
  publishing: "ESSA_PUBLISHING",
  books: "ESSA_BOOKS",
  mirror: "ESSA_MIRROR",
  business: "ESSA_BUSINESS",
  advertising: "ESSA_ADVERTISING",
  creatorNetwork: "ESSA_CREATOR_NETWORK",
  property: "ESSA_PROPERTY",
  developer: "ESSA_DEVELOPER",
  kidsLumi: "ESSA_KIDS_LUMI",
  voice: "ESSA_VOICE",
  research: "ESSA_RESEARCH",
  workspace: "ESSA_WORKSPACE"
};

export const productCapabilityMap = {
  [productIds.navigator]: ["QUESTION_GENERATION", "DOCUMENTATION_LOOKUP", "SOURCE_COMPARE"],
  [productIds.production]: ["SEMANTIC_ANALYZE", "VIDEO_EDIT", "VIDEO_CAPTION", "MEDIA_PROBE", "VIDEO_TRIM", "VIDEO_RESIZE", "AUDIO_EXTRACT", "VIDEO_EXPORT", "AUDIO_MIX", "CONTENT_ANALYZE", "CONTENT_PERFORMANCE_ANALYZE", "CONTENT_ATTRIBUTION", "CONTENT_ECONOMICS", "CONTENT_LEARN", "NEXT_CONTENT_RECOMMEND", "VIRAL_PATTERN_ANALYZE", "FACELESS_CHANNEL_BUILD", "CONTENT_EXPERIMENT", "OFFER_AWARE_CONTENT_PLAN"],
  [productIds.musicFactory]: ["MUSIC_ANALYZE", "VOCAL_REPLACE", "STEM_SEPARATE", "ARRANGEMENT_TRANSFORM", "MIX", "MASTER", "MUSIC_EXPORT"],
  [productIds.publishing]: ["BOOK_STRUCTURE", "TEXT_EDIT", "DOCUMENT_FORMAT", "BOOK_COVER", "EBOOK_BUILD", "AUDIOBOOK_BUILD", "PUBLISHING_PACKAGE"],
  [productIds.books]: ["BOOK_STRUCTURE", "TEXT_EDIT", "BOOK_COVER", "EBOOK_BUILD", "AUDIOBOOK_BUILD"],
  [productIds.mirror]: ["PATTERN_REFLECTION", "QUESTION_GENERATION", "REFLECTION_SUMMARY", "PATTERN_TIMELINE"],
  [productIds.business]: ["BUSINESS_ANALYZE", "BUSINESS_AUDIT", "BUSINESS_GROWTH_PLAN", "BUSINESS_SALE_PREP", "MARKETING_PLAN", "BUSINESS_DISCOVERY", "BUSINESS_ENTITY_VERIFY", "BUSINESS_DATA_NORMALIZE", "BUSINESS_DEDUPLICATE", "LEAD_QUALIFY", "LEAD_SCORE", "BUSINESS_NEED_ANALYZE", "ESSA_FIT_MATCH", "LEAD_EXPORT", "OFFER_AWARE_CONTENT_PLAN", "CONTENT_ECONOMICS", "CONTENT_ATTRIBUTION"],
  [productIds.advertising]: ["CREATIVE_BRIEF", "AD_CREATIVE_GENERATE", "CAMPAIGN_PLAN", "PERFORMANCE_ANALYZE", "BUSINESS_DISCOVERY", "BUSINESS_NEED_ANALYZE", "ESSA_FIT_MATCH", "LEAD_QUALIFY", "OUTREACH_PREPARE", "CONTENT_PERFORMANCE_ANALYZE", "CONTENT_ATTRIBUTION", "CONTENT_EXPERIMENT", "CAMPAIGN_INTELLIGENCE"],
  [productIds.creatorNetwork]: ["CREATOR_MATCH", "CREATIVE_BRIEF", "CONTENT_PLAN", "BUSINESS_DISCOVERY", "ESSA_FIT_MATCH", "OUTREACH_PREPARE", "CONTENT_ANALYZE", "CONTENT_ATTRIBUTION", "NEXT_CONTENT_RECOMMEND", "FACELESS_CHANNEL_BUILD"],
  [productIds.property]: ["PROPERTY_ANALYZE", "PROPERTY_ADD_INTAKE", "PROPERTY_PRESENTATION", "INVESTMENT_PACKAGE", "DEVELOPMENT_CONCEPT", "PROPERTY_MARKETING", "BUSINESS_DISCOVERY", "BUSINESS_ENTITY_VERIFY", "BUSINESS_NEED_ANALYZE"],
  [productIds.developer]: ["WEBSITE_GENERATE", "APP_GENERATE", "CODE_GENERATE", "CODE_EDIT", "CODE_REVIEW", "CODE_DEBUG", "DATABASE_DESIGN", "API_INTEGRATE", "BUSINESS_DISCOVERY"],
  [productIds.kidsLumi]: ["LESSON_GENERATE", "STORY_GENERATE", "EDUCATIONAL_EXPLAIN", "KIDS_CONTENT_PLAN"],
  [productIds.voice]: ["AUDIO_TRANSCRIBE", "VOICE_GENERATE", "VOICE_REPLACE", "VOICE_TRANSLATE", "AUDIO_CLEAN"],
  [productIds.research]: ["DOCUMENTATION_LOOKUP", "WEB_RESEARCH", "SOURCE_COMPARE", "FACT_EXTRACT"],
  [productIds.workspace]: ["WEBSITE_GENERATE", "DOCUMENT_GENERATE", "BROWSER_OBSERVE", "UI_VERIFY", "AUTOMATION_BUILD"]
};

export function getProductCapabilities(productId) {
  return [...(productCapabilityMap[productId] || [])];
}

export function getProductsForCapability(capabilityId) {
  return Object.entries(productCapabilityMap)
    .filter(([, capabilities]) => capabilities.includes(capabilityId))
    .map(([productId]) => productId);
}
